alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias -- -='cd -'

alias ls='ls --color=auto'
alias l='ls -lhF'
alias la='ls -AlhF'
alias ll='ls -alhF'
alias grep='grep --color=auto'
alias g='git'
alias dotfiles='git --git-dir="$HOME/.dotfiles" --work-tree="$HOME"'
alias reload='exec bash -l'
alias path='printf "%s\n" "$PATH" | tr ":" "\n"'
